import { createFileRoute } from '@tanstack/react-router';
import { queryOptions, useSuspenseQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { BRL } from '@/lib/calc';
import { toast } from 'sonner';
const adminQuery=queryOptions({queryKey:['admin-referrals'],queryFn:async()=>{const {data,error}=await supabase.from('referral_redemptions').select('*,profiles!referral_redemptions_user_id_fkey(nome)').order('created_at',{ascending:false}).limit(200);if(error)throw error;return data;}});
export const Route=createFileRoute('/_authenticated/admin/indicacoes')({head:()=>({meta:[{title:'Resgates de indicação — Admin — Entrega Pro'},{name:'description',content:'Aprovação e histórico de resgates de indicação.'},{property:'og:title',content:'Resgates de indicação — Entrega Pro'},{property:'og:description',content:'Gerencie solicitações de Pix e desconto.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'},{name:'robots',content:'noindex'}]}),loader:({context})=>context.queryClient.ensureQueryData(adminQuery),pendingComponent:()=> <p>Carregando resgates…</p>,errorComponent:({reset})=><div><p>Não foi possível carregar os resgates.</p><Button onClick={reset}>Tentar novamente</Button></div>,component:AdminReferrals});
function AdminReferrals(){const {data}=useSuspenseQuery(adminQuery);const qc=useQueryClient();const [decision,setDecision]=useState<{id:string;approve:boolean;kind:string}|null>(null);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('pending');async function submit(e:React.FormEvent){e.preventDefault();if(!decision||busy)return;setBusy(true);try{const {error}=await supabase.rpc('decide_referral_redemption',{_id:decision.id,_approve:decision.approve,_reason:reason});if(error)throw error;await qc.invalidateQueries({queryKey:['admin-referrals']});await qc.invalidateQueries({queryKey:['referrals']});setDecision(null);setReason('');toast.success('Decisão registrada');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível registrar');}finally{setBusy(false);}}
return <><h1 className="text-xl font-bold">Resgates de indicação</h1><div className="flex gap-2 my-4">{[['pending','Pendentes'],['all','Histórico']].map(([v,l])=><Button key={v} variant={filter===v?'default':'secondary'} onClick={()=>setFilter(v)}>{l}</Button>)}</div><div className="space-y-3">{data.filter(r=>filter==='all'||r.status==='pending').map(r=><article className="ep-card" key={r.id}><div className="flex justify-between gap-2"><h2 className="font-semibold">{r.profiles?.nome||'Motorista'}</h2><strong>{BRL(Number(r.amount))}</strong></div><p className="text-sm mt-2">{r.kind==='pix'?'Pix':`Desconto no plano ${r.plan}`} · {r.status==='pending'?'Em análise':r.status==='approved'?'Aprovado':'Recusado'}</p>{r.pix_key&&<p className="text-sm break-all mt-2">Chave Pix: {r.pix_key}</p>}<p className="text-xs text-muted-foreground mt-2">{new Date(r.created_at).toLocaleString('pt-BR')}{r.reason?` · ${r.reason}`:''}</p>{r.status==='pending'&&<div className="flex flex-wrap gap-2 mt-3"><Button onClick={()=>{setReason('');setDecision({id:r.id,approve:true,kind:r.kind});}}>{r.kind==='pix'?'Registrar Pix pago':'Aprovar desconto'}</Button><Button variant="destructive" onClick={()=>{setReason('');setDecision({id:r.id,approve:false,kind:r.kind});}}>Recusar</Button></div>}</article>)}{!data.some(r=>filter==='all'||r.status==='pending')&&<p className="text-muted-foreground py-6">Nenhum resgate nesta lista.</p>}</div><Dialog open={decision!==null} onOpenChange={o=>{if(!o&&!busy)setDecision(null);}}><DialogContent><DialogHeader><DialogTitle>{decision?.approve?'Confirmar aprovação':'Recusar resgate'}</DialogTitle><DialogDescription>{decision?.approve&&decision.kind==='pix'?'Faça o Pix antes de confirmar. Informe a referência do pagamento.':decision?.approve?'O desconto será aplicado à solicitação Premium.':'O saldo reservado será devolvido.'}</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-3"><label className="block text-sm">Motivo ou referência<textarea required minLength={3} maxLength={300} className="ep-input mt-1" value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy} type="submit">{busy?'Registrando…':'Confirmar'}</Button></form></DialogContent></Dialog></>;}
