/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedResumoRouteImport } from './routes/_authenticated/resumo'
import { Route as AuthenticatedRecebimentosRouteImport } from './routes/_authenticated/recebimentos'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedManutencaoRouteImport } from './routes/_authenticated/manutencao'
import { Route as AuthenticatedMaisRouteImport } from './routes/_authenticated/mais'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedGraficosRouteImport } from './routes/_authenticated/graficos'
import { Route as AuthenticatedContaExcluidaRouteImport } from './routes/_authenticated/conta-excluida'
import { Route as AuthenticatedAbastecimentosRouteImport } from './routes/_authenticated/abastecimentos'
import { Route as AuthenticatedFinanceiroRouteRouteImport } from './routes/_authenticated/financeiro/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPerfilNotificacoesRouteImport } from './routes/_authenticated/perfil/notificacoes'
import { Route as AuthenticatedLancamentoIdRouteImport } from './routes/_authenticated/lancamento.$id'
import { Route as AuthenticatedFinanceiroPixRouteImport } from './routes/_authenticated/financeiro/pix'
import { Route as AuthenticatedFinanceiroMetasRouteImport } from './routes/_authenticated/financeiro/metas'
import { Route as AuthenticatedFinanceiroMeiRouteImport } from './routes/_authenticated/financeiro/mei'
import { Route as AuthenticatedFinanceiroFluxoRouteImport } from './routes/_authenticated/financeiro/fluxo'
import { Route as AuthenticatedFinanceiroContasRouteImport } from './routes/_authenticated/financeiro/contas'
import { Route as AuthenticatedFinanceiroCartoesRouteImport } from './routes/_authenticated/financeiro/cartoes'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminSolicitacoesRouteImport } from './routes/_authenticated/admin/solicitacoes'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as ApiPublicHooksPurgeContasRouteImport } from './routes/api/public/hooks/purge-contas'
import { Route as ApiPublicHooksNotificacoesDiariasRouteImport } from './routes/api/public/hooks/notificacoes-diarias'
import { Route as AuthenticatedPerfilNotificacoesTesteRouteImport } from './routes/_authenticated/perfil/notificacoes.teste'
import { Route as AuthenticatedPerfilNotificacoesLogsRouteImport } from './routes/_authenticated/perfil/notificacoes.logs'
import { Route as AuthenticatedPerfilNotificacoesDiagnosticoRouteImport } from './routes/_authenticated/perfil/notificacoes.diagnostico'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumoRoute = AuthenticatedResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecebimentosRoute =
  AuthenticatedRecebimentosRouteImport.update({
    id: '/recebimentos',
    path: '/recebimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencaoRoute = AuthenticatedManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaisRoute = AuthenticatedMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGraficosRoute = AuthenticatedGraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaExcluidaRoute =
  AuthenticatedContaExcluidaRouteImport.update({
    id: '/conta-excluida',
    path: '/conta-excluida',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbastecimentosRoute =
  AuthenticatedAbastecimentosRouteImport.update({
    id: '/abastecimentos',
    path: '/abastecimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRouteRoute =
  AuthenticatedFinanceiroRouteRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilNotificacoesRoute =
  AuthenticatedPerfilNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedLancamentoIdRoute =
  AuthenticatedLancamentoIdRouteImport.update({
    id: '/lancamento/$id',
    path: '/lancamento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroPixRoute =
  AuthenticatedFinanceiroPixRouteImport.update({
    id: '/pix',
    path: '/pix',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroMetasRoute =
  AuthenticatedFinanceiroMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroMeiRoute =
  AuthenticatedFinanceiroMeiRouteImport.update({
    id: '/mei',
    path: '/mei',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroFluxoRoute =
  AuthenticatedFinanceiroFluxoRouteImport.update({
    id: '/fluxo',
    path: '/fluxo',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasRoute =
  AuthenticatedFinanceiroContasRouteImport.update({
    id: '/contas',
    path: '/contas',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroCartoesRoute =
  AuthenticatedFinanceiroCartoesRouteImport.update({
    id: '/cartoes',
    path: '/cartoes',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSolicitacoesRoute =
  AuthenticatedAdminSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksPurgeContasRoute =
  ApiPublicHooksPurgeContasRouteImport.update({
    id: '/api/public/hooks/purge-contas',
    path: '/api/public/hooks/purge-contas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificacoesDiariasRoute =
  ApiPublicHooksNotificacoesDiariasRouteImport.update({
    id: '/api/public/hooks/notificacoes-diarias',
    path: '/api/public/hooks/notificacoes-diarias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPerfilNotificacoesTesteRoute =
  AuthenticatedPerfilNotificacoesTesteRouteImport.update({
    id: '/teste',
    path: '/teste',
    getParentRoute: () => AuthenticatedPerfilNotificacoesRoute,
  } as any)
const AuthenticatedPerfilNotificacoesLogsRoute =
  AuthenticatedPerfilNotificacoesLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedPerfilNotificacoesRoute,
  } as any)
const AuthenticatedPerfilNotificacoesDiagnosticoRoute =
  AuthenticatedPerfilNotificacoesDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedPerfilNotificacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRouteRouteWithChildren
  '/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/conta-excluida': typeof AuthenticatedContaExcluidaRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/premium': typeof AuthenticatedPremiumRoute
  '/recebimentos': typeof AuthenticatedRecebimentosRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/financeiro/mei': typeof AuthenticatedFinanceiroMeiRoute
  '/financeiro/metas': typeof AuthenticatedFinanceiroMetasRoute
  '/financeiro/pix': typeof AuthenticatedFinanceiroPixRoute
  '/lancamento/$id': typeof AuthenticatedLancamentoIdRoute
  '/perfil/notificacoes': typeof AuthenticatedPerfilNotificacoesRouteWithChildren
  '/perfil/notificacoes/diagnostico': typeof AuthenticatedPerfilNotificacoesDiagnosticoRoute
  '/perfil/notificacoes/logs': typeof AuthenticatedPerfilNotificacoesLogsRoute
  '/perfil/notificacoes/teste': typeof AuthenticatedPerfilNotificacoesTesteRoute
  '/api/public/hooks/notificacoes-diarias': typeof ApiPublicHooksNotificacoesDiariasRoute
  '/api/public/hooks/purge-contas': typeof ApiPublicHooksPurgeContasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRouteRouteWithChildren
  '/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/conta-excluida': typeof AuthenticatedContaExcluidaRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/premium': typeof AuthenticatedPremiumRoute
  '/recebimentos': typeof AuthenticatedRecebimentosRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/financeiro/mei': typeof AuthenticatedFinanceiroMeiRoute
  '/financeiro/metas': typeof AuthenticatedFinanceiroMetasRoute
  '/financeiro/pix': typeof AuthenticatedFinanceiroPixRoute
  '/lancamento/$id': typeof AuthenticatedLancamentoIdRoute
  '/perfil/notificacoes': typeof AuthenticatedPerfilNotificacoesRouteWithChildren
  '/perfil/notificacoes/diagnostico': typeof AuthenticatedPerfilNotificacoesDiagnosticoRoute
  '/perfil/notificacoes/logs': typeof AuthenticatedPerfilNotificacoesLogsRoute
  '/perfil/notificacoes/teste': typeof AuthenticatedPerfilNotificacoesTesteRoute
  '/api/public/hooks/notificacoes-diarias': typeof ApiPublicHooksNotificacoesDiariasRoute
  '/api/public/hooks/purge-contas': typeof ApiPublicHooksPurgeContasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteRouteWithChildren
  '/_authenticated/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/_authenticated/conta-excluida': typeof AuthenticatedContaExcluidaRoute
  '/_authenticated/graficos': typeof AuthenticatedGraficosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/mais': typeof AuthenticatedMaisRoute
  '/_authenticated/manutencao': typeof AuthenticatedManutencaoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/recebimentos': typeof AuthenticatedRecebimentosRoute
  '/_authenticated/resumo': typeof AuthenticatedResumoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/_authenticated/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/_authenticated/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/_authenticated/financeiro/mei': typeof AuthenticatedFinanceiroMeiRoute
  '/_authenticated/financeiro/metas': typeof AuthenticatedFinanceiroMetasRoute
  '/_authenticated/financeiro/pix': typeof AuthenticatedFinanceiroPixRoute
  '/_authenticated/lancamento/$id': typeof AuthenticatedLancamentoIdRoute
  '/_authenticated/perfil/notificacoes': typeof AuthenticatedPerfilNotificacoesRouteWithChildren
  '/_authenticated/perfil/notificacoes/diagnostico': typeof AuthenticatedPerfilNotificacoesDiagnosticoRoute
  '/_authenticated/perfil/notificacoes/logs': typeof AuthenticatedPerfilNotificacoesLogsRoute
  '/_authenticated/perfil/notificacoes/teste': typeof AuthenticatedPerfilNotificacoesTesteRoute
  '/api/public/hooks/notificacoes-diarias': typeof ApiPublicHooksNotificacoesDiariasRoute
  '/api/public/hooks/purge-contas': typeof ApiPublicHooksPurgeContasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/admin'
    | '/financeiro'
    | '/abastecimentos'
    | '/conta-excluida'
    | '/graficos'
    | '/historico'
    | '/mais'
    | '/manutencao'
    | '/perfil'
    | '/premium'
    | '/recebimentos'
    | '/resumo'
    | '/admin/configuracoes'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/financeiro/cartoes'
    | '/financeiro/contas'
    | '/financeiro/fluxo'
    | '/financeiro/mei'
    | '/financeiro/metas'
    | '/financeiro/pix'
    | '/lancamento/$id'
    | '/perfil/notificacoes'
    | '/perfil/notificacoes/diagnostico'
    | '/perfil/notificacoes/logs'
    | '/perfil/notificacoes/teste'
    | '/api/public/hooks/notificacoes-diarias'
    | '/api/public/hooks/purge-contas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/admin'
    | '/financeiro'
    | '/abastecimentos'
    | '/conta-excluida'
    | '/graficos'
    | '/historico'
    | '/mais'
    | '/manutencao'
    | '/perfil'
    | '/premium'
    | '/recebimentos'
    | '/resumo'
    | '/'
    | '/admin/configuracoes'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/financeiro/cartoes'
    | '/financeiro/contas'
    | '/financeiro/fluxo'
    | '/financeiro/mei'
    | '/financeiro/metas'
    | '/financeiro/pix'
    | '/lancamento/$id'
    | '/perfil/notificacoes'
    | '/perfil/notificacoes/diagnostico'
    | '/perfil/notificacoes/logs'
    | '/perfil/notificacoes/teste'
    | '/api/public/hooks/notificacoes-diarias'
    | '/api/public/hooks/purge-contas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/financeiro'
    | '/_authenticated/abastecimentos'
    | '/_authenticated/conta-excluida'
    | '/_authenticated/graficos'
    | '/_authenticated/historico'
    | '/_authenticated/mais'
    | '/_authenticated/manutencao'
    | '/_authenticated/perfil'
    | '/_authenticated/premium'
    | '/_authenticated/recebimentos'
    | '/_authenticated/resumo'
    | '/_authenticated/'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/solicitacoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/financeiro/cartoes'
    | '/_authenticated/financeiro/contas'
    | '/_authenticated/financeiro/fluxo'
    | '/_authenticated/financeiro/mei'
    | '/_authenticated/financeiro/metas'
    | '/_authenticated/financeiro/pix'
    | '/_authenticated/lancamento/$id'
    | '/_authenticated/perfil/notificacoes'
    | '/_authenticated/perfil/notificacoes/diagnostico'
    | '/_authenticated/perfil/notificacoes/logs'
    | '/_authenticated/perfil/notificacoes/teste'
    | '/api/public/hooks/notificacoes-diarias'
    | '/api/public/hooks/purge-contas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ApiPublicHooksNotificacoesDiariasRoute: typeof ApiPublicHooksNotificacoesDiariasRoute
  ApiPublicHooksPurgeContasRoute: typeof ApiPublicHooksPurgeContasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumo': {
      id: '/_authenticated/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AuthenticatedResumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recebimentos': {
      id: '/_authenticated/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof AuthenticatedRecebimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencao': {
      id: '/_authenticated/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mais': {
      id: '/_authenticated/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedMaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/graficos': {
      id: '/_authenticated/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof AuthenticatedGraficosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta-excluida': {
      id: '/_authenticated/conta-excluida'
      path: '/conta-excluida'
      fullPath: '/conta-excluida'
      preLoaderRoute: typeof AuthenticatedContaExcluidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimentos': {
      id: '/_authenticated/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/abastecimentos'
      preLoaderRoute: typeof AuthenticatedAbastecimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/notificacoes': {
      id: '/_authenticated/perfil/notificacoes'
      path: '/notificacoes'
      fullPath: '/perfil/notificacoes'
      preLoaderRoute: typeof AuthenticatedPerfilNotificacoesRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/lancamento/$id': {
      id: '/_authenticated/lancamento/$id'
      path: '/lancamento/$id'
      fullPath: '/lancamento/$id'
      preLoaderRoute: typeof AuthenticatedLancamentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/pix': {
      id: '/_authenticated/financeiro/pix'
      path: '/pix'
      fullPath: '/financeiro/pix'
      preLoaderRoute: typeof AuthenticatedFinanceiroPixRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/metas': {
      id: '/_authenticated/financeiro/metas'
      path: '/metas'
      fullPath: '/financeiro/metas'
      preLoaderRoute: typeof AuthenticatedFinanceiroMetasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/mei': {
      id: '/_authenticated/financeiro/mei'
      path: '/mei'
      fullPath: '/financeiro/mei'
      preLoaderRoute: typeof AuthenticatedFinanceiroMeiRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/fluxo': {
      id: '/_authenticated/financeiro/fluxo'
      path: '/fluxo'
      fullPath: '/financeiro/fluxo'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/contas': {
      id: '/_authenticated/financeiro/contas'
      path: '/contas'
      fullPath: '/financeiro/contas'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/cartoes': {
      id: '/_authenticated/financeiro/cartoes'
      path: '/cartoes'
      fullPath: '/financeiro/cartoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroCartoesRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/solicitacoes': {
      id: '/_authenticated/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/purge-contas': {
      id: '/api/public/hooks/purge-contas'
      path: '/api/public/hooks/purge-contas'
      fullPath: '/api/public/hooks/purge-contas'
      preLoaderRoute: typeof ApiPublicHooksPurgeContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notificacoes-diarias': {
      id: '/api/public/hooks/notificacoes-diarias'
      path: '/api/public/hooks/notificacoes-diarias'
      fullPath: '/api/public/hooks/notificacoes-diarias'
      preLoaderRoute: typeof ApiPublicHooksNotificacoesDiariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil/notificacoes/teste': {
      id: '/_authenticated/perfil/notificacoes/teste'
      path: '/teste'
      fullPath: '/perfil/notificacoes/teste'
      preLoaderRoute: typeof AuthenticatedPerfilNotificacoesTesteRouteImport
      parentRoute: typeof AuthenticatedPerfilNotificacoesRoute
    }
    '/_authenticated/perfil/notificacoes/logs': {
      id: '/_authenticated/perfil/notificacoes/logs'
      path: '/logs'
      fullPath: '/perfil/notificacoes/logs'
      preLoaderRoute: typeof AuthenticatedPerfilNotificacoesLogsRouteImport
      parentRoute: typeof AuthenticatedPerfilNotificacoesRoute
    }
    '/_authenticated/perfil/notificacoes/diagnostico': {
      id: '/_authenticated/perfil/notificacoes/diagnostico'
      path: '/diagnostico'
      fullPath: '/perfil/notificacoes/diagnostico'
      preLoaderRoute: typeof AuthenticatedPerfilNotificacoesDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedPerfilNotificacoesRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminSolicitacoesRoute: typeof AuthenticatedAdminSolicitacoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminSolicitacoesRoute: AuthenticatedAdminSolicitacoesRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedFinanceiroRouteRouteChildren {
  AuthenticatedFinanceiroCartoesRoute: typeof AuthenticatedFinanceiroCartoesRoute
  AuthenticatedFinanceiroContasRoute: typeof AuthenticatedFinanceiroContasRoute
  AuthenticatedFinanceiroFluxoRoute: typeof AuthenticatedFinanceiroFluxoRoute
  AuthenticatedFinanceiroMeiRoute: typeof AuthenticatedFinanceiroMeiRoute
  AuthenticatedFinanceiroMetasRoute: typeof AuthenticatedFinanceiroMetasRoute
  AuthenticatedFinanceiroPixRoute: typeof AuthenticatedFinanceiroPixRoute
}

const AuthenticatedFinanceiroRouteRouteChildren: AuthenticatedFinanceiroRouteRouteChildren =
  {
    AuthenticatedFinanceiroCartoesRoute: AuthenticatedFinanceiroCartoesRoute,
    AuthenticatedFinanceiroContasRoute: AuthenticatedFinanceiroContasRoute,
    AuthenticatedFinanceiroFluxoRoute: AuthenticatedFinanceiroFluxoRoute,
    AuthenticatedFinanceiroMeiRoute: AuthenticatedFinanceiroMeiRoute,
    AuthenticatedFinanceiroMetasRoute: AuthenticatedFinanceiroMetasRoute,
    AuthenticatedFinanceiroPixRoute: AuthenticatedFinanceiroPixRoute,
  }

const AuthenticatedFinanceiroRouteRouteWithChildren =
  AuthenticatedFinanceiroRouteRoute._addFileChildren(
    AuthenticatedFinanceiroRouteRouteChildren,
  )

interface AuthenticatedPerfilNotificacoesRouteChildren {
  AuthenticatedPerfilNotificacoesDiagnosticoRoute: typeof AuthenticatedPerfilNotificacoesDiagnosticoRoute
  AuthenticatedPerfilNotificacoesLogsRoute: typeof AuthenticatedPerfilNotificacoesLogsRoute
  AuthenticatedPerfilNotificacoesTesteRoute: typeof AuthenticatedPerfilNotificacoesTesteRoute
}

const AuthenticatedPerfilNotificacoesRouteChildren: AuthenticatedPerfilNotificacoesRouteChildren =
  {
    AuthenticatedPerfilNotificacoesDiagnosticoRoute:
      AuthenticatedPerfilNotificacoesDiagnosticoRoute,
    AuthenticatedPerfilNotificacoesLogsRoute:
      AuthenticatedPerfilNotificacoesLogsRoute,
    AuthenticatedPerfilNotificacoesTesteRoute:
      AuthenticatedPerfilNotificacoesTesteRoute,
  }

const AuthenticatedPerfilNotificacoesRouteWithChildren =
  AuthenticatedPerfilNotificacoesRoute._addFileChildren(
    AuthenticatedPerfilNotificacoesRouteChildren,
  )

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilNotificacoesRoute: typeof AuthenticatedPerfilNotificacoesRouteWithChildren
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilNotificacoesRoute:
    AuthenticatedPerfilNotificacoesRouteWithChildren,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFinanceiroRouteRoute: typeof AuthenticatedFinanceiroRouteRouteWithChildren
  AuthenticatedAbastecimentosRoute: typeof AuthenticatedAbastecimentosRoute
  AuthenticatedContaExcluidaRoute: typeof AuthenticatedContaExcluidaRoute
  AuthenticatedGraficosRoute: typeof AuthenticatedGraficosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMaisRoute: typeof AuthenticatedMaisRoute
  AuthenticatedManutencaoRoute: typeof AuthenticatedManutencaoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedRecebimentosRoute: typeof AuthenticatedRecebimentosRoute
  AuthenticatedResumoRoute: typeof AuthenticatedResumoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLancamentoIdRoute: typeof AuthenticatedLancamentoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFinanceiroRouteRoute:
    AuthenticatedFinanceiroRouteRouteWithChildren,
  AuthenticatedAbastecimentosRoute: AuthenticatedAbastecimentosRoute,
  AuthenticatedContaExcluidaRoute: AuthenticatedContaExcluidaRoute,
  AuthenticatedGraficosRoute: AuthenticatedGraficosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMaisRoute: AuthenticatedMaisRoute,
  AuthenticatedManutencaoRoute: AuthenticatedManutencaoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedRecebimentosRoute: AuthenticatedRecebimentosRoute,
  AuthenticatedResumoRoute: AuthenticatedResumoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLancamentoIdRoute: AuthenticatedLancamentoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ApiPublicHooksNotificacoesDiariasRoute:
    ApiPublicHooksNotificacoesDiariasRoute,
  ApiPublicHooksPurgeContasRoute: ApiPublicHooksPurgeContasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
