/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedResumoRouteImport } from './routes/_authenticated/resumo'
import { Route as AuthenticatedRecebimentosRouteImport } from './routes/_authenticated/recebimentos'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedManutencaoRouteImport } from './routes/_authenticated/manutencao'
import { Route as AuthenticatedMaisRouteImport } from './routes/_authenticated/mais'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedGraficosRouteImport } from './routes/_authenticated/graficos'
import { Route as AuthenticatedAbastecimentosRouteImport } from './routes/_authenticated/abastecimentos'
import { Route as AuthenticatedFinanceiroRouteRouteImport } from './routes/_authenticated/financeiro/route'
import { Route as AuthenticatedLancamentoIdRouteImport } from './routes/_authenticated/lancamento.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumoRoute = AuthenticatedResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecebimentosRoute =
  AuthenticatedRecebimentosRouteImport.update({
    id: '/recebimentos',
    path: '/recebimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencaoRoute = AuthenticatedManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaisRoute = AuthenticatedMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGraficosRoute = AuthenticatedGraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbastecimentosRoute =
  AuthenticatedAbastecimentosRouteImport.update({
    id: '/abastecimentos',
    path: '/abastecimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRouteRoute =
  AuthenticatedFinanceiroRouteRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentoIdRoute =
  AuthenticatedLancamentoIdRouteImport.update({
    id: '/lancamento/$id',
    path: '/lancamento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteRoute
  '/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/recebimentos': typeof AuthenticatedRecebimentosRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/lancamento/$id': typeof AuthenticatedLancamentoIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteRoute
  '/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/recebimentos': typeof AuthenticatedRecebimentosRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/': typeof AuthenticatedIndexRoute
  '/lancamento/$id': typeof AuthenticatedLancamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteRoute
  '/_authenticated/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/_authenticated/graficos': typeof AuthenticatedGraficosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/mais': typeof AuthenticatedMaisRoute
  '/_authenticated/manutencao': typeof AuthenticatedManutencaoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/recebimentos': typeof AuthenticatedRecebimentosRoute
  '/_authenticated/resumo': typeof AuthenticatedResumoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/lancamento/$id': typeof AuthenticatedLancamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/financeiro'
    | '/abastecimentos'
    | '/graficos'
    | '/historico'
    | '/mais'
    | '/manutencao'
    | '/perfil'
    | '/premium'
    | '/recebimentos'
    | '/resumo'
    | '/lancamento/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/financeiro'
    | '/abastecimentos'
    | '/graficos'
    | '/historico'
    | '/mais'
    | '/manutencao'
    | '/perfil'
    | '/premium'
    | '/recebimentos'
    | '/resumo'
    | '/'
    | '/lancamento/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/financeiro'
    | '/_authenticated/abastecimentos'
    | '/_authenticated/graficos'
    | '/_authenticated/historico'
    | '/_authenticated/mais'
    | '/_authenticated/manutencao'
    | '/_authenticated/perfil'
    | '/_authenticated/premium'
    | '/_authenticated/recebimentos'
    | '/_authenticated/resumo'
    | '/_authenticated/'
    | '/_authenticated/lancamento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumo': {
      id: '/_authenticated/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AuthenticatedResumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recebimentos': {
      id: '/_authenticated/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof AuthenticatedRecebimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencao': {
      id: '/_authenticated/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mais': {
      id: '/_authenticated/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedMaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/graficos': {
      id: '/_authenticated/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof AuthenticatedGraficosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimentos': {
      id: '/_authenticated/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/abastecimentos'
      preLoaderRoute: typeof AuthenticatedAbastecimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamento/$id': {
      id: '/_authenticated/lancamento/$id'
      path: '/lancamento/$id'
      fullPath: '/lancamento/$id'
      preLoaderRoute: typeof AuthenticatedLancamentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFinanceiroRouteRoute: typeof AuthenticatedFinanceiroRouteRoute
  AuthenticatedAbastecimentosRoute: typeof AuthenticatedAbastecimentosRoute
  AuthenticatedGraficosRoute: typeof AuthenticatedGraficosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMaisRoute: typeof AuthenticatedMaisRoute
  AuthenticatedManutencaoRoute: typeof AuthenticatedManutencaoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedRecebimentosRoute: typeof AuthenticatedRecebimentosRoute
  AuthenticatedResumoRoute: typeof AuthenticatedResumoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLancamentoIdRoute: typeof AuthenticatedLancamentoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFinanceiroRouteRoute: AuthenticatedFinanceiroRouteRoute,
  AuthenticatedAbastecimentosRoute: AuthenticatedAbastecimentosRoute,
  AuthenticatedGraficosRoute: AuthenticatedGraficosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMaisRoute: AuthenticatedMaisRoute,
  AuthenticatedManutencaoRoute: AuthenticatedManutencaoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedRecebimentosRoute: AuthenticatedRecebimentosRoute,
  AuthenticatedResumoRoute: AuthenticatedResumoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLancamentoIdRoute: AuthenticatedLancamentoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
